image: oraclejdk8

cache:
  - /home/ubuntu/.m2/repository

env:
  - AWS_ACCESS_KEY_ID=$$AWS_ACCESS_KEY_ID
  - AWS_SECRET_ACCESS_KEY=$$AWS_SECRET_ACCESS_KEY
  - EC2_KEY_NAME=$$EC2_KEY_NAME
  - AWSEB_S3_BUCKET=$$AWSEB_S3_BUCKET
  - SONAR_HOST=$$SONAR_HOST
  - SONAR_JDBC_HOST=$$SONAR_JDBC_HOST
  - SONAR_JDBC_PASSWORD=$$SONAR_JDBC_PASSWORD
  - NEXUS_USER=$$NEXUS_USER
  - NEXUS_PASSWORD=$$NEXUS_PASSWORD
  - MAVEN_VERSION=3.3.3
  - M2_HOME=/home/ubuntu/.mvm/3.3.3
  - MAVEN_OPTS=-Xmx2048m -Xmn1536m
  - BOOTSTRAP_KEY=$$BOOTSTRAP_KEY

script:
  - curl -sSL http://stedolan.github.io/jq/download/linux64/jq > /tmp/jq && chmod 755 /tmp/jq
  - if [ -f .bootstrap.sh ]; then source .bootstrap.sh ; fi
  - (curl -sSL https://raw.github.com/ingenieux/mvm/master/install.sh | bash 2>&1 >/dev/null)
  - sudo chown -R ubuntu:ubuntu $HOME/.m2 $HOME/.mvm
  - source ~/.mvm/mvm.sh && mvm install $MAVEN_VERSION && mvm alias default $MAVEN_VERSION
  - cp ci/settings.xml $HOME/.m2/settings.xml
  - mvn -B -e clean install
  - mvn -B -e verify site -Dbeanstalk.project.name=mbit-drone -Ptest,it
  - if [ ! -z "$BOOTSTRAP_KEY" ]; then curl -sSL "$BOOTSTRAP_KEY" | /tmp/jq -r .node.value - | bash ; mvn -B -e -Psonatype-oss-release clean package site deploy site-deploy ; fi

#
#notify:
#  email:
#    recipients:
#      - brad@drone.io
#  gitter:
#    room_id: $$GITTER_ROOM
#    token: $$GITTER_KEY
#    on_started: false
#    on_success: true
#    on_failure: true
